### ISSUE TITLE
How to get the dataset

### ISSUE THREAD

**Issue by yy9568** [Irene323/GFTE#1]
Thank you for your great job, how can we get the dataset?

**Comment by yy9568** [comment]
@Irene323

**Comment by lsr12345** [comment]
same question, THX

**Comment by vanche** [comment]
same here. :) do you have plan to release dataset?

**Comment by arnyao** [comment]
same question

**Comment by afaq-ahmad** [comment]
@Irene323  you did great work. Kindly open-source the dataset as well.

**Comment by afaq-ahmad** [comment]
SciTSR Dataset can be downloaded from here https://github.com/Academic-Hammer/SciTSR

**Comment by yy9568** [comment]
@afaq-ahmad Thank you very much.

**Comment by afaq-ahmad** [comment]
@zhouyuangan FinTab Dataset still not available yet.
